[package]
name = "pngme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.47"
anyhow = "1.0.75"
crc = "3.0.1"
clap = { version = "4.3.22", features = ["derive"] }
